import type { Meal } from '@/types/common'

export const mockMeals: Meal[] = [
  {
    id: '1',
    name: 'Kung Pao Chicken Rice Bowl',
    nameZh: '宫保鸡丁盖饭',
    description: 'Diced chicken stir-fried with peanuts, vegetables, and chili peppers in savory sauce over steamed rice',
    descriptionZh: '嫩滑鸡丁配花生米、蔬菜和辣椒，用香浓酱汁炒制，配白米饭',
    category: 'RICE_BASED',
    price: 16.99,
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop&q=80',
    allergens: ['nuts', 'soy'],
    isActive: true,
    inventory: 25,
    calories: 580,
    protein: 35,
    carbs: 65,
    fat: 18,
    ingredients: 'Chicken breast, peanuts, bell peppers, onions, celery, dried chili peppers, garlic, ginger, soy sauce, rice wine, cornstarch, sesame oil, steamed rice',
    isSpicy: true,
    featured: true
  },
  {
    id: '2',
    name: 'Taiwanese Beef Noodle Soup',
    nameZh: '台湾牛肉面',
    description: 'Tender braised beef in rich, aromatic broth with hand-pulled noodles and bok choy',
    descriptionZh: '精选牛肉配浓郁高汤，手工拉面配小白菜',
    category: 'NOODLE_SOUPS',
    price: 18.99,
    imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&h=400&fit=crop&q=80',
    allergens: ['gluten', 'soy'],
    isActive: true,
    inventory: 20,
    calories: 650,
    protein: 40,
    carbs: 75,
    fat: 15,
    ingredients: 'Beef chuck, hand-pulled noodles, bok choy, onions, garlic, ginger, star anise, soy sauce, bean paste, beef stock, scallions',
    isSpicy: false,
    featured: true
  },
  {
    id: '3',
    name: 'Creamy Mushroom Chicken Pasta',
    nameZh: '奶油蘑菇鸡肉意面',
    description: 'Grilled chicken breast with sautéed mushrooms in a rich cream sauce over penne pasta',
    descriptionZh: '烤鸡胸肉配炒蘑菇，浓郁奶油酱汁配通心粉',
    category: 'PASTA_FUSION',
    price: 17.99,
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&h=400&fit=crop&q=80',
    allergens: ['gluten', 'dairy'],
    isActive: true,
    inventory: 30,
    calories: 620,
    protein: 38,
    carbs: 55,
    fat: 22,
    ingredients: 'Chicken breast, penne pasta, mixed mushrooms, heavy cream, garlic, onions, parmesan cheese, parsley, white wine, olive oil',
    isSpicy: false,
    featured: false
  },
  {
    id: '4',
    name: 'Teriyaki Salmon with Quinoa',
    nameZh: '照烧三文鱼配藜麦',
    description: 'Glazed salmon fillet with steamed vegetables and protein-rich quinoa',
    descriptionZh: '照烧三文鱼配蒸蔬菜和营养丰富的藜麦',
    category: 'PROTEIN_SIDES',
    price: 21.99,
    imageUrl: 'https://images.unsplash.com/photo-1580959375944-abd7e991f971?w=600&h=400&fit=crop&q=80',
    allergens: ['fish', 'soy'],
    isActive: true,
    inventory: 15,
    calories: 520,
    protein: 42,
    carbs: 35,
    fat: 20,
    ingredients: 'Atlantic salmon, quinoa, broccoli, carrots, snap peas, teriyaki sauce, sesame seeds, ginger, garlic',
    isSpicy: false,
    featured: false
  },
  {
    id: '5',
    name: 'Szechuan Mapo Tofu Rice',
    nameZh: '四川麻婆豆腐盖饭',
    description: 'Silky tofu in spicy Szechuan sauce with ground pork over jasmine rice',
    descriptionZh: '嫩滑豆腐配四川麻辣酱汁和肉末，配茉莉香米',
    category: 'RICE_BASED',
    price: 15.99,
    imageUrl: 'https://images.unsplash.com/photo-1583349443162-de4280f65e4c?w=600&h=400&fit=crop&q=80',
    allergens: ['soy'],
    isActive: true,
    inventory: 22,
    calories: 540,
    protein: 25,
    carbs: 68,
    fat: 16,
    ingredients: 'Silky tofu, ground pork, jasmine rice, Szechuan peppercorns, doubanjiang, garlic, ginger, scallions, soy sauce, cornstarch',
    isSpicy: true,
    featured: false
  },
  {
    id: '6',
    name: 'Mediterranean Herb Chicken',
    nameZh: '地中海香草鸡肉',
    description: 'Herb-crusted chicken breast with roasted vegetables and lemon couscous',
    descriptionZh: '香草烤鸡胸肉配烤蔬菜和柠檬库斯库斯',
    category: 'PROTEIN_SIDES',
    price: 19.99,
    imageUrl: 'https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=600&h=400&fit=crop&q=80',
    allergens: ['gluten'],
    isActive: true,
    inventory: 18,
    calories: 590,
    protein: 45,
    carbs: 42,
    fat: 18,
    ingredients: 'Chicken breast, couscous, zucchini, bell peppers, cherry tomatoes, herbs (oregano, thyme, basil), lemon, olive oil, garlic',
    isSpicy: false,
    featured: false
  }
]